name: Metalprot_learning
channels:
  - defaults
dependencies:
  - python=3.9.12
  - torchvision
  - pytorch
  - pandas
  - pip:
    - numpy==1.22.4
    - prody==2.2.0
    - scipy==1.8.1
    - optuna==2.10.0
    - docopt==0.6.2
    - pypivoter==0.1.0
    - scikit-learn==1.1.1
prefix: /opt/anaconda3/envs/Metalprot_learning
